DROP TABLE ACCOUNT

CREATE TABLE ACCOUNT (
ACCOUNT_ID			INTEGER			NOT NULL,
CUSTOMER_ID			INTEGER			NOT NULL,
ACCOUNT_BALANCE		DECIMAL(8,2)	NOT NULL,
ACCOUNT_TYPE		VARCHAR(8)		NOT NULL
primary key (ACCOUNT_ID)
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID));

INSERT INTO ACCOUNT VALUES(1, 1, 456.02, 'Savings');

select * from ACCOUNT;