drop table CUSTOMER

CREATE TABLE CUSTOMER (
CUSTOMER_ID			INTEGER			NOT NULL,
CUSTOMER_FNAME		VARCHAR(15)		NOT NULL,
CUSTOMER_LNAME		VARCHAR(25)		NOT NULL,
CUSTOMER_GENDER		VARCHAR(1),
CUSTOMER_DOB		DATE			NOT NULL,
CUSTOMER_ADDRESS	VARCHAR(95)		NOT NULL,
CUSTOMER_CITY		VARCHAR(35)		NOT NULL,
CUSTOMER_STATE		VARCHAR(2)		NOT NULL,
CUSTOMER_PIN		INTEGER			NOT NULL,
CUSTOMER_AREACODE	INTEGER			NOT NULL,
CUSTOMER_CO			INTEGER			NOT NULL,
CUSTOMER_LINE		INTEGER			NOT NULL,
CUSTOMER_EMAIL		VARCHAR(65)		NOT NULL,
CUSTOMER_PASSWORD	VARCHAR(25)		NOT NULL
primary key (CUSTOMER_ID));