DROP TABLE CUSTOMER

CREATE TABLE CUSTOMER (
CUSTOMER_ID			INTEGER			NOT NULL,
CUSTOMER_FNAME		VARCHAR(15)		NOT NULL,
CUSTOMER_LNAME		VARCHAR(25)		NOT NULL,
CUSTOMER_GENDER		VARCHAR(1),
CUSTOMER_DOB		DATE			NOT NULL,
CUSTOMER_ADDRESS	VARCHAR(95)		NOT NULL,
CUSTOMER_CITY		VARCHAR(35)		NOT NULL,
CUSTOMER_STATE		VARCHAR(2)		NOT NULL,
CUSTOMER_PIN		VARCHAR(6)		NOT NULL,
CUSTOMER_AREACODE	VARCHAR(3)		NOT NULL,
CUSTOMER_CO			VARCHAR(3)		NOT NULL,
CUSTOMER_LINE		VARCHAR(4)		NOT NULL,
CUSTOMER_EMAIL		VARCHAR(65)		NOT NULL,
CUSTOMER_PASSWORD	VARCHAR(25)		NOT NULL
primary key (CUSTOMER_ID));

INSERT INTO CUSTOMER VALUES(1, 'John', 'Doe', 'M', '1995-05-13', '123 Street Avenue', 'Hell', 'MI', '895354', '248', '513', '0737', 'email@email.com', 'password');

select * from CUSTOMER;