drop table MANAGER

CREATE TABLE MANAGER (
MANAGER_ID			INTEGER			NOT NULL,
MANAGER_FNAME		VARCHAR(1)		NOT NULL,
MANAGER_LNAME		VARCHAR(25)		NOT NULL,
CUSTOMER_EMAIL		VARCHAR(65)		NOT NULL,
CUSTOMER_PASSWORD	VARCHAR(25)		NOT NULL
primary key (MANAGER_ID));