DROP TABLE MANAGER

CREATE TABLE MANAGER (
MANAGER_ID			INTEGER			NOT NULL,
MANAGER_FNAME		VARCHAR(15)		NOT NULL,
MANAGER_LNAME		VARCHAR(25)		NOT NULL,
MANAGER_EMAIL		VARCHAR(65)		NOT NULL,
MANAGER_PASSWORD	VARCHAR(25)		NOT NULL
primary key (MANAGER_ID));

INSERT INTO MANAGER VALUES(1, 'Jane', 'Doe', 'email@email.com', 'password');

select * from MANAGER;